import src.database2.schema.balance_sheet as BalanceSheetSchema
from src.database2.schema.balance_sheet import Base
from src.database2.database_helpers import get_engine
from sqlalchemy.orm import sessionmaker

engine = get_engine()
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
db = SessionLocal()

def create_tables():
    Base.metadata.create_all(engine)
    print("Tables created successfully.")

def add_static_data_for_balance_sheet_item_standardized():
    static_data = [
        ('100', 'short_term_assets'),
        ('110', 'cash_and_cash_equivalents'),
        ('111', 'cash'),
        ('112', 'cash_equivalents'),
        ('120', 'short_term_financial_investments'),
        ('121', 'trading_securities'),
        ('122', 'provision_for_decrease_in_value_of_trading_securities'),
        ('123', 'short_term_investments_held_to_maturity'),
        ('130', 'short_term_receivables'),
        ('131', 'short_term_receivables_from_customers'),
        ('132', 'prepayments_to_sellers_in_short_term'),
        ('133', 'short_term_intercompany_receivables'),
        ('134', 'receivables_according_to_the_progress_of_construction_com'),
        ('135', 'short_term_loan_receivables'),
        ('136', 'other_short_term_receivables'),
        ('137', 'provision_for_uncollectible_short_term_receivables'),
        ('139', 'shortage_of_assets_awaiting_resolution'),
        ('140', 'inventories_total'),
        ('141', 'inventories'),
        ('149', 'provision_against_devaluation_of_goods_in_stock'),
        ('150', 'other_short_term_assets_total'),
        ('151', 'short_term_prepaid_expenses'),
        ('152', 'deductible_vat'),
        ('153', 'taxes_and_other_revenues_to_the_state'),
        ('154', 'purchase_and_resale_of_government_bonds'),
        ('155', 'other_short_term_assets'),
        ('200', 'long_term_assets'),
        ('210', 'long_term_receivables'),
        ('211', 'long_term_receivables_from_customers'),
        ('212', 'prepayments_to_suppliers_in_long_term'),
        ('213', 'working_capital_provided_to_subordinate_units'),
        ('214', 'long_term_intercompany_receivables'),
        ('215', 'receivables_on_long_term_loans'),
        ('216', 'other_long_term_receivables'),
        ('219', 'provision_for_doubtful_long_term_receivables'),
        ('220', 'fixed_assets'),
        ('221', 'tangible_fixed_assets'),
        ('222', 'tangible_fixed_assets_historical_costs'),
        ('223', 'tangible_fixed_assets_value_of_accumulated_depreciation'),
        ('224', 'finance_lease_fixed_asset'),
        ('225', 'finance_lease_fixed_asset_historical_costs'),
        ('226', 'finance_lease_fixed_asset_value_of_accumulated_depreciation'),
        ('227', 'intangible_fixed_assets'),
        ('228', 'intangible_fixed_assets_historical_costs'),
        ('229', 'intangible_fixed_assets_value_of_accumulated_depreciation'),
        ('230', 'investment_real_property'),
        ('231', 'investment_real_property_historical_costs'),
        ('232', 'investment_real_property_value_of_accumulated_depreciation'),
        ('240', 'long_term_unfinished_assets'),
        ('241', 'cost_of_long_term_work_in_progress'),
        ('242', 'cost_of_construction_in_progress'),
        ('250', 'long_term_financial_investments'),
        ('251', 'investments_in_subsidiaries'),
        ('252', 'investments_in_associated_companies_and_joint_ventures'),
        ('253', 'investments_in_other_units'),
        ('254', 'provisions_for_long_term_financial_investments'),
        ('255', 'long_term_investments_held_to_maturity'),
        ('260', 'other_long_term_assets_total'),
        ('261', 'long_term_prepaid_expenses'),
        ('262', 'deferred_income_tax_assets'),
        ('263', 'long_term_equipment_supplies_and_spare_parts'),
        ('268', 'other_long_term_assets'),
        ('270', 'total_assets'),
        ('300', 'liabilities'),
        ('310', 'short_term_debt'),
        ('311', 'short_term_supplier_payables'),
        ('312', 'short_term_deferred_revenues'),
        ('313', 'taxes_and_other_payables_to_state'),
        ('314', 'payables_to_employees'),
        ('315', 'short_term_expenses_payable'),
        ('316', 'short_term_intercompany_payables'),
        ('317', 'payables_according_to_the_progress_of_construction_contract'),
        ('318', 'short_term_unearned_revenue'),
        ('319', 'other_short_term_payables'),
        ('320', 'short_term_loans_and_finance_lease_liabilities'),
        ('321', 'provision_for_short_term_payables'),
        ('322', 'bonus_and_welfare_fund'),
        ('323', 'price_stabilization_fund'),
        ('324', 'purchase_and_resale_of_government_bonds'),
        ('330', 'long_term_liabilities'),
        ('331', 'long_term_supplier_payables'),
        ('332', 'long_term_deferred_revenues'),
        ('333', 'long_term_expenses_payable'),
        ('334', 'intercompany_payables_on_working_capital'),
        ('335', 'long_term_intercompany_payables'),
        ('336', 'long_term_unearned_revenue'),
        ('337', 'other_long_term_payables'),
        ('338', 'long_term_loans_and_finance_lease_liabilities'),
        ('339', 'convertible_bonds'),
        ('340', 'long_term_liabilities_preference_shares'),
        ('341', 'deferred_income_tax'),
        ('342', 'provision_for_long_term_payables'),
        ('343', 'scientific_and_technological_development_fund'),
        ('400', 'owner_equity_total'),
        ('410', 'owner_equity'),
        ('411', 'contributions_from_owners'),
        ('411a', 'ordinary_shares_with_voting_rights'),
        ('411b', 'owner_equity_preference_shares'),
        ('412', 'share_premium'),
        ('413', 'conversion_options_on_bond'),
        ('414', 'other_capital_of_owners'),
        ('415', 'treasury_shares'),
        ('416', 'differences_upon_asset_revaluation'),
        ('417', 'exchange_differences'),
        ('418', 'development_investment_funds'),
        ('419', 'enterprise_reorganization_assistance_fund'),
        ('420', 'other_equity_fund'),
        ('421', 'undistributed_post_tax_profits'),
        ('421a', 'undistributed_post_tax_profits_accumulated_end_of_prv_period'),
        ('421b', 'undistributed_post_tax_profits_of_current_period'),
        ('422', 'capital_expenditure_fund'),
        ('430', 'funding_and_other_funds'),
        ('431', 'funding'),
        ('432', 'funds_that_form_fixed_assets'),
        ('440', 'total_capital')
    ]
    for code, name in static_data:
        item = BalanceSheetSchema.BalanceSheetItemStandardizedORM(code=code, name=name)
        db.add(item)
        db.flush()

    db.commit()

if __name__ == "__main__":
    create_tables()
    add_static_data_for_balance_sheet_item_standardized()