from sqlalchemy import Column, Integer, Float, String, Date, ForeignKey, DateTime, DECIMAL
from sqlalchemy.sql import func
from sqlalchemy.orm import declarative_base, relationship
from dotenv import load_dotenv
import os

load_dotenv(override=True)
Base = declarative_base()

class BalanceSheetAtEndOfPeriodORM(Base):
    __tablename__ = os.getenv("BALANCE_SHEET_EOP_TABLE_NAME")

    id = Column(Integer, primary_key=True)
    company_name = Column(String(255), nullable=False, index=True)
    stock_code = Column(String(20), nullable=True)
    period_end_date = Column(Date, nullable=False)
    currency = Column(String(10), default="VND")
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

    short_term_assets = Column(DECIMAL(20, 2), comment='Total value of all current assets expected to be converted to cash within one year | Tổng giá trị tất cả tài sản ngắn hạn dự kiến chuyển đổi thành tiền trong vòng một năm')
    cash_and_cash_equivalents = Column(DECIMAL(20, 2), comment='Highly liquid assets including cash and short-term investments | Tài sản có tính thanh khoản cao bao gồm tiền mặt và các khoản đầu tư ngắn hạn')
    cash = Column(DECIMAL(20, 2), comment='Physical currency, coins, and balances in checking accounts | Tiền mặt vật lý, tiền xu và số dư trong tài khoản séc')
    cash_equivalents = Column(DECIMAL(20, 2), comment='Short-term, highly liquid investments that are readily convertible to cash | Các khoản đầu tư ngắn hạn, có tính thanh khoản cao dễ dàng chuyển đổi thành tiền mặt')
    short_term_financial_investments = Column(DECIMAL(20, 2), comment='Investments intended to be held for less than one year | Các khoản đầu tư tài chính dự định nắm giữ dưới một năm')
    trading_securities = Column(DECIMAL(20, 2), comment='Securities bought and held principally for selling in the near term | Chứng khoán mua và nắm giữ chủ yếu để bán trong thời gian ngắn')
    provision_for_decrease_in_value_of_trading_securities = Column(DECIMAL(20, 2), comment='Allowance for potential loss in value of trading securities | Dự phòng cho khoản lỗ tiềm tàng về giá trị của chứng khoán kinh doanh')
    short_term_investments_held_to_maturity = Column(DECIMAL(20, 2), comment='Debt securities the company intends to hold until maturity and are due within one year | Chứng khoán nợ mà công ty dự định nắm giữ đến ngày đáo hạn và có thời hạn dưới một năm')
    short_term_receivables = Column(DECIMAL(20, 2), comment='Amounts expected to be received within one year | Các khoản dự kiến sẽ nhận được trong vòng một năm')
    short_term_receivables_from_customers = Column(DECIMAL(20, 2), comment='Amounts owed by customers that are due within one year | Các khoản khách hàng nợ đến hạn trong vòng một năm')
    prepayments_to_sellers_in_short_term = Column(DECIMAL(20, 2), comment='Advance payments made to suppliers for goods or services to be received within one year | Thanh toán trước cho nhà cung cấp đối với hàng hóa hoặc dịch vụ sẽ nhận được trong vòng một năm')
    short_term_intercompany_receivables = Column(DECIMAL(20, 2), comment='Amounts owed to the company by related entities within one year | Các khoản các thực thể liên quan nợ công ty trong vòng một năm')
    receivables_according_to_the_progress_of_construction_com = Column(DECIMAL(20, 2), comment='Amounts receivable based on percentage of completion of construction contracts | Các khoản phải thu theo tiến độ hoàn thành hợp đồng xây dựng')
    short_term_loan_receivables = Column(DECIMAL(20, 2), comment='Short-term loans made to others that are due within one year | Các khoản cho vay ngắn hạn đến hạn trong vòng một năm')
    other_short_term_receivables = Column(DECIMAL(20, 2), comment='Other amounts due to the company within one year not elsewhere classified | Các khoản phải thu ngắn hạn khác không được phân loại ở nơi khác')
    provision_for_uncollectible_short_term_receivables = Column(DECIMAL(20, 2), comment='Allowance for doubtful short-term receivables | Dự phòng cho các khoản phải thu ngắn hạn khó đòi')
    shortage_of_assets_awaiting_resolution = Column(DECIMAL(20, 2), comment='Shortages of assets that are pending investigation and resolution | Thiếu hụt tài sản đang chờ điều tra và giải quyết')
    inventories_total = Column(DECIMAL(20, 2), comment='Total value of goods held for sale or in production | Tổng giá trị hàng hóa nắm giữ để bán hoặc trong sản xuất')
    inventories = Column(DECIMAL(20, 2), comment='Raw materials, work in progress and finished goods | Nguyên liệu, sản phẩm dở dang và thành phẩm')
    provision_against_devaluation_of_goods_in_stock = Column(DECIMAL(20, 2), comment='Allowance for potential loss in value of inventory | Dự phòng giảm giá hàng tồn kho')
    other_short_term_assets_total = Column(DECIMAL(20, 2), comment='Total of other current assets not elsewhere classified | Tổng các tài sản ngắn hạn khác không được phân loại ở nơi khác')
    short_term_prepaid_expenses = Column(DECIMAL(20, 2), comment='Expenses paid in advance that will be recognized within one year | Chi phí trả trước sẽ được ghi nhận trong vòng một năm')
    deductible_vat = Column(DECIMAL(20, 2), comment='Value added tax that can be deducted | Giá trị gia tăng được khấu trừ')
    taxes_and_other_revenues_to_the_state = Column(DECIMAL(20, 2), comment='Taxes and other amounts payable to government authorities | Thuế và các khoản khác phải nộp nhà nước')
    purchase_and_resale_of_government_bonds = Column(DECIMAL(20, 2), comment='Government bonds purchased for resale | Trái phiếu chính phủ mua để bán lại')
    other_short_term_assets = Column(DECIMAL(20, 2), comment='Other current assets not elsewhere specified | Các tài sản ngắn hạn khác không được chỉ định ở nơi khác')
    long_term_assets = Column(DECIMAL(20, 2), comment='Assets that provide value for more than one year | Tài sản cung cấp giá trị trong hơn một năm')
    long_term_receivables = Column(DECIMAL(20, 2), comment='Amounts expected to be received after one year | Các khoản dự kiến sẽ nhận được sau một năm')
    long_term_receivables_from_customers = Column(DECIMAL(20, 2), comment='Amounts owed by customers that are due after one year | Các khoản khách hàng nợ đến hạn sau một năm')
    prepayments_to_suppliers_in_long_term = Column(DECIMAL(20, 2), comment='Advance payments made to suppliers for goods or services to be received after one year | Thanh toán trước cho nhà cung cấp đối với hàng hóa hoặc dịch vụ sẽ nhận được sau một năm')
    working_capital_provided_to_subordinate_units = Column(DECIMAL(20, 2), comment='Capital provided to subsidiaries and affiliates | Vốn lưu động cung cấp cho các đơn vị trực thuộc')
    long_term_intercompany_receivables = Column(DECIMAL(20, 2), comment='Amounts owed to the company by related entities after one year | Các khoản các thực thể liên quan nợ công ty sau một năm')
    receivables_on_long_term_loans = Column(DECIMAL(20, 2), comment='Long-term loans made to others | Các khoản cho vay dài hạn cho bên khác')
    other_long_term_receivables = Column(DECIMAL(20, 2), comment='Other amounts due to the company after one year not elsewhere classified | Các khoản phải thu dài hạn khác không được phân loại ở nơi khác')
    provision_for_doubtful_long_term_receivables = Column(DECIMAL(20, 2), comment='Allowance for doubtful long-term receivables | Dự phòng cho các khoản phải thu dài hạn khó đòi')
    fixed_assets = Column(DECIMAL(20, 2), comment='Long-term tangible and intangible assets used in operations | Tài sản hữu hình và vô hình dài hạn sử dụng trong hoạt động')
    tangible_fixed_assets = Column(DECIMAL(20, 2), comment='Physical assets used in operations | Tài sản cố định hữu hình')
    tangible_fixed_assets_historical_costs = Column(DECIMAL(20, 2), comment='Original acquisition cost of tangible fixed assets | Nguyên giá tài sản cố định hữu hình')
    tangible_fixed_assets_value_of_accumulated_depreciation = Column(DECIMAL(20, 2), comment='Total depreciation accumulated on tangible fixed assets | Giá trị hao mòn lũy kế tài sản cố định hữu hình')
    finance_lease_fixed_asset = Column(DECIMAL(20, 2), comment='Assets acquired under finance lease arrangements | Tài sản thuê tài chính')
    finance_lease_fixed_asset_historical_costs = Column(DECIMAL(20, 2), comment='Original cost of finance leased assets | Nguyên giá tài sản thuê tài chính')
    finance_lease_fixed_asset_value_of_accumulated_depreciation = Column(DECIMAL(20, 2), comment='Total depreciation accumulated on finance leased assets | Giá trị hao mòn lũy kế tài sản thuê tài chính')
    intangible_fixed_assets = Column(DECIMAL(20, 2), comment='Non-physical assets with long-term value | Tài sản cố định vô hình')
    intangible_fixed_assets_historical_costs = Column(DECIMAL(20, 2), comment='Original acquisition cost of intangible fixed assets | Nguyên giá tài sản cố định vô hình')
    intangible_fixed_assets_value_of_accumulated_depreciation = Column(DECIMAL(20, 2), comment='Total amortization accumulated on intangible fixed assets | Giá trị hao mòn lũy kế tài sản cố định vô hình')
    investment_real_property = Column(DECIMAL(20, 2), comment='Real estate held for investment purposes | Bất động sản đầu tư')
    investment_real_property_historical_costs = Column(DECIMAL(20, 2), comment='Original acquisition cost of investment property | Nguyên giá bất động sản đầu tư')
    investment_real_property_value_of_accumulated_depreciation = Column(DECIMAL(20, 2), comment='Total depreciation accumulated on investment property | Giá trị hao mòn lũy kế bất động sản đầu tư')
    long_term_unfinished_assets = Column(DECIMAL(20, 2), comment='Assets under construction or development | Tài sản dở dang dài hạn')
    cost_of_long_term_work_in_progress = Column(DECIMAL(20, 2), comment='Costs incurred for long-term projects not yet completed | Chi phí cho các dự án dài hạn chưa hoàn thành')
    cost_of_construction_in_progress = Column(DECIMAL(20, 2), comment='Costs incurred for construction projects not yet completed | Chi phí xây dựng dở dang')
    long_term_financial_investments = Column(DECIMAL(20, 2), comment='Investments intended to be held for more than one year | Đầu tư tài chính dài hạn')
    investments_in_subsidiaries = Column(DECIMAL(20, 2), comment='Investments in companies where the parent has control | Đầu tư vào công ty con')
    investments_in_associated_companies_and_joint_ventures = Column(DECIMAL(20, 2), comment='Investments in companies where the investor has significant influence | Đầu tư vào công ty liên kết và liên doanh')
    investments_in_other_units = Column(DECIMAL(20, 2), comment='Other long-term equity investments | Đầu tư vào các đơn vị khác')
    provisions_for_long_term_financial_investments = Column(DECIMAL(20, 2), comment='Allowance for potential loss on long-term investments | Dự phòng giảm giá đầu tư tài chính dài hạn')
    long_term_investments_held_to_maturity = Column(DECIMAL(20, 2), comment='Debt securities the company intends to hold until maturity and are due after one year | Chứng khoán nợ mà công ty dự định nắm giữ đến ngày đáo hạn và có thời hạn trên một năm')
    other_long_term_assets_total = Column(DECIMAL(20, 2), comment='Total of other non-current assets not elsewhere classified | Tổng các tài sản dài hạn khác không được phân loại ở nơi khác')
    long_term_prepaid_expenses = Column(DECIMAL(20, 2), comment='Expenses paid in advance that will be recognized after one year | Chi phí trả trước dài hạn')
    deferred_income_tax_assets = Column(DECIMAL(20, 2), comment='Taxes paid in advance or tax benefits to be realized in future periods | Tài sản thuế thu nhập hoãn lại')
    long_term_equipment_supplies_and_spare_parts = Column(DECIMAL(20, 2), comment='Long-term inventory of equipment and spare parts | Vật tư, phụ tùng thay thế dài hạn')
    other_long_term_assets = Column(DECIMAL(20, 2), comment='Other non-current assets not elsewhere specified | Tài sản dài hạn khác')

    total_assets = Column(DECIMAL(20, 2), comment='Sum of all assets | Tổng tài sản')

    # --- LIABILITIES & EQUITY ---
    liabilities = Column(DECIMAL(20, 2), comment='Total obligations owed to external parties including both short-term and long-term debts | Tổng các khoản nợ phải trả cho bên ngoài bao gồm nợ ngắn hạn và dài hạn')
    short_term_debt = Column(DECIMAL(20, 2), comment='Obligations due within one year | Nợ ngắn hạn')
    short_term_supplier_payables = Column(DECIMAL(20, 2), comment='Amounts owed to suppliers due within one year | Phải trả người bán ngắn hạn')
    short_term_deferred_revenues = Column(DECIMAL(20, 2), comment='Payments received in advance for services to be provided within one year | Doanh thu chưa thực hiện ngắn hạn')
    taxes_and_other_payables_to_state = Column(DECIMAL(20, 2), comment='Taxes and other amounts payable to government within one year | Thuế và các khoản phải nộp nhà nước ngắn hạn')
    payables_to_employees = Column(DECIMAL(20, 2), comment='Wages and benefits owed to employees | Phải trả người lao động')
    short_term_expenses_payable = Column(DECIMAL(20, 2), comment='Accrued expenses to be paid within one year | Chi phí phải trả ngắn hạn')
    short_term_intercompany_payables = Column(DECIMAL(20, 2), comment='Amounts owed to related entities within one year | Phải trả nội bộ ngắn hạn')
    payables_according_to_the_progress_of_construction_contract = Column(DECIMAL(20, 2), comment='Amounts payable based on percentage of completion of construction contracts | Phải trả theo tiến độ hợp đồng xây dựng')
    short_term_unearned_revenue = Column(DECIMAL(20, 2), comment='Payments received for services not yet performed | Doanh thu chưa thực hiện ngắn hạn')
    other_short_term_payables = Column(DECIMAL(20, 2), comment='Other current liabilities not elsewhere classified | Các khoản phải trả ngắn hạn khác')
    short_term_loans_and_finance_lease_liabilities = Column(DECIMAL(20, 2), comment='Short-term borrowings and lease obligations | Vay ngắn hạn và nợ thuê tài chính ngắn hạn')
    provision_for_short_term_payables = Column(DECIMAL(20, 2), comment='Allowance for uncertain short-term liabilities | Dự phòng phải trả ngắn hạn')
    bonus_and_welfare_fund = Column(DECIMAL(20, 2), comment='Reserves for employee bonuses and welfare | Quỹ khen thưởng, phúc lợi')
    price_stabilization_fund = Column(DECIMAL(20, 2), comment='Reserve for price stabilization purposes | Quỹ bình ổn giá')
    long_term_liabilities = Column(DECIMAL(20, 2), comment='Obligations due after one year | Nợ dài hạn')
    long_term_supplier_payables = Column(DECIMAL(20, 2), comment='Amounts owed to suppliers due after one year | Phải trả người bán dài hạn')
    long_term_deferred_revenues = Column(DECIMAL(20, 2), comment='Payments received in advance for services to be provided after one year | Doanh thu chưa thực hiện dài hạn')
    long_term_expenses_payable = Column(DECIMAL(20, 2), comment='Accrued expenses to be paid after one year | Chi phí phải trả dài hạn')
    intercompany_payables_on_working_capital = Column(DECIMAL(20, 2), comment='Amounts owed to related entities for working capital | Phải trả nội bộ về vốn kinh doanh')
    long_term_intercompany_payables = Column(DECIMAL(20, 2), comment='Amounts owed to related entities after one year | Phải trả nội bộ dài hạn')
    long_term_unearned_revenue = Column(DECIMAL(20, 2), comment='Payments received for services to be performed after one year | Doanh thu chưa thực hiện dài hạn')
    other_long_term_payables = Column(DECIMAL(20, 2), comment='Other non-current liabilities not elsewhere classified | Các khoản phải trả dài hạn khác')
    long_term_loans_and_finance_lease_liabilities = Column(DECIMAL(20, 2), comment='Long-term borrowings and lease obligations | Vay dài hạn và nợ thuê tài chính dài hạn')
    convertible_bonds = Column(DECIMAL(20, 2), comment='Bonds that can be converted into equity | Trái phiếu chuyển đổi')
    long_term_liabilities_preference_shares = Column(DECIMAL(20, 2), comment='Preferred shares classified as liabilities | Cổ phiếu ưu đãi xếp vào nợ phải trả')
    deferred_income_tax = Column(DECIMAL(20, 2), comment='Taxes payable in future periods | Thuế thu nhập hoãn lại phải trả')
    provision_for_long_term_payables = Column(DECIMAL(20, 2), comment='Allowance for uncertain long-term liabilities | Dự phòng phải trả dài hạn')
    scientific_and_technological_development_fund = Column(DECIMAL(20, 2), comment='Reserve for research and development activities | Quỹ phát triển khoa học và công nghệ')
    owner_equity_total = Column(DECIMAL(20, 2), comment='Total owners equity | Tổng vốn chủ sở hữu')
    owner_equity = Column(DECIMAL(20, 2), comment='Owners claim on company assets | Vốn chủ sở hữu')
    contributions_from_owners = Column(DECIMAL(20, 2), comment='Capital contributed by owners | Vốn góp của chủ sở hữu')
    ordinary_shares_with_voting_rights = Column(DECIMAL(20, 2), comment='Common stock with voting privileges | Cổ phiếu phổ thông có quyền biểu quyết')
    owner_equity_preference_shares = Column(DECIMAL(20, 2), comment='Preferred shares classified as equity | Cổ phiếu ưu đãi xếp vào vốn chủ sở hữu')
    share_premium = Column(DECIMAL(20, 2), comment='Amount received above par value of shares | Thặng dư vốn cổ phần')
    conversion_options_on_bond = Column(DECIMAL(20, 2), comment='Value of conversion options on convertible bonds | Quyền chọn chuyển đổi trái phiếu')
    other_capital_of_owners = Column(DECIMAL(20, 2), comment='Other capital contributions from owners | Vốn khác của chủ sở hữu')
    treasury_shares = Column(DECIMAL(20, 2), comment='Company own shares repurchased | Cổ phiếu quỹ')
    differences_upon_asset_revaluation = Column(DECIMAL(20, 2), comment='Gains/losses from asset revaluations | Chênh lệch đánh giá lại tài sản')
    exchange_differences = Column(DECIMAL(20, 2), comment='Gains/losses from currency translation | Chênh lệch tỷ giá')
    development_investment_funds = Column(DECIMAL(20, 2), comment='Reserves for development and investment | Quỹ đầu tư phát triển')
    enterprise_reorganization_assistance_fund = Column(DECIMAL(20, 2), comment='Reserve for enterprise restructuring | Quỹ hỗ trợ sắp xếp doanh nghiệp')
    other_equity_fund = Column(DECIMAL(20, 2), comment='Other equity reserves | Quỹ khác thuộc vốn chủ sở hữu')
    undistributed_post_tax_profits = Column(DECIMAL(20, 2), comment='Retained earnings | Lợi nhuận sau thuế chưa phân phối')
    undistributed_post_tax_profits_accumulated_end_of_prv_period = Column(DECIMAL(20, 2), comment='Retained earnings from prior periods | Lợi nhuận sau thuế chưa phân phối lũy kế đến cuối kỳ trước')
    undistributed_post_tax_profits_of_current_period = Column(DECIMAL(20, 2), comment='Current period net income not yet distributed | Lợi nhuận sau thuế chưa phân phối kỳ hiện tại')
    capital_expenditure_fund = Column(DECIMAL(20, 2), comment='Reserve for capital expenditures | Quỹ đầu tư phát triển')
    funding_and_other_funds = Column(DECIMAL(20, 2), comment='Government grants and other funding | Nguồn kinh phí và quỹ khác')
    funding = Column(DECIMAL(20, 2), comment='Government financial assistance | Nguồn kinh phí')
    funds_that_form_fixed_assets = Column(DECIMAL(20, 2), comment='Funding used to acquire fixed assets | Nguồn vốn đầu tư XDCB')
    total_capital = Column(DECIMAL(20, 2), comment='Total liabilities and equity | Tổng nguồn vốn')

    def __repr__(self):
        return f"<BalanceSheet(id={self.id}, company_id={self.company_id}, period_end_date='{self.period_end_date}')>"

class BalanceSheetItemStandardizedORM(Base):
    __tablename__ = os.getenv("BALANCE_SHEET_ITEMS_STANDARDIZED_TABLE_NAME")

    id = Column(Integer, primary_key=True)
    code = Column(String(10), unique=True, nullable=False)
    name = Column(String(255), nullable=False)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

    def __repr__(self):
        return f"<BalanceSheetItemStandardizedORM(id={self.id}, code='{self.code}', name='{self.name}')>"